FROM tiangolo/meinheld-gunicorn-flask:python3.7 AS Shavano_Home

ENV APP_MODULE=Main:app
ENV PORT=8080

RUN groupadd -g 999 appuser && \
    useradd -r -u 999 -g appuser appuser && \
    mkdir /home/appuser && \
    chown -R appuser:appuser /home/appuser && \
    chown -R appuser:appuser /app
USER appuser

COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt --user
