AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS resources for MedFoyer backend
Parameters: 
        EnvType: 
                Description: Environment type.
                Default: sandbox
                Type: String
                AllowedValues: 
                        - prod
                        - dev
                        - sandbox
                ConstraintDescription: must specify valid stage [prod|dev|sandbox].
Resources:
        GetAppointment:
                Type: AWS::Serverless::Function
                Properties:
                        FunctionName: !Sub "${EnvType}-get-appointment"
                        Handler: handlers/appointment.handler
                        Runtime: python3.8
                        CodeUri: ./
        CheckInAppointment:
                Type: AWS::Serverless::Function
                Properties:
                        FunctionName: !Sub "${EnvType}-check-in-appointment"
                        Handler: handlers/appointment.check_in_handler
                        Runtime: python3.8
                        CodeUri: ./
        SubmitAppointmentForm:
                Type: AWS::Serverless::Function
                Properties:
                        FunctionName: !Sub "${EnvType}-submit-appointment-form"
                        Handler: handlers/appointment.submit_form_handler
                        Runtime: python3.8
                        CodeUri: ./
        SummonPatient:
                Type: AWS::Serverless::Function
                Properties:
                        FunctionName: !Sub "${EnvType}-summon-patient-appointment"
                        Handler: handlers/appointment.summon_patient_handler
                        Runtime: python3.8
                        CodeUri: ./
